### ISSUE TITLE
HALLink should be Serializable

### ISSUE THREAD

**Issue by resah** [openapi-tools/jackson-dataformat-hal#22]
There are many cases in which one want to cache the API results, which is currently not as easy as it could be. To work around the missing `Serializable` implementation I had to write custom serialization classes for `HALLink`.

Since caching of API results is a very common and implementation is really easy, I recommend making `HALLink` implement `Serializable`.

**Comment by langecode** [comment]
True, I see no reason why we could not make `HALLink` `Serializable`. I will create a release with this change.

**Comment by langecode** [comment]
Fixed with 9814afb3086191a5edc56870447cbfcae02f4dab - will be contained in next release.
