### ISSUE TITLE
Conflict with JsonTypeInfo for Polymorphic Classes

### ISSUE THREAD

**Issue by Phil404** [openapi-tools/jackson-dataformat-hal#25]
Problem:
We are using polymorphic classes in our API.
Unfortunately the HAL structure don't get created when its come to serialization.
We tried every possible combination of the @JsonTypeInfo annotation and nothing "really" changed.
Maybe you have an Idea or a Solution.
Currently we can't use your Library as it proposed to.

Deserialization is not effected so far.
Related Pull Request: https://github.com/openapi-tools/jackson-dataformat-hal/pull/24
Pipeline is failing as expected, because I added all possible cases for the polymorphic classes

**Comment by langecode** [comment]
Indeed it seems that in this case the annotations of the HAL extensions is not picked up correctly. I will try to find some time to look into this. Thanks for providing the test cases.

**Comment by Phil404** [comment]
> Indeed it seems that in this case the annotations of the HAL extensions is not picked up correctly. I will try to find some time to look into this. Thanks for providing the test cases.

Thank you very much!
