### ISSUE TITLE
Allow non templated String links

### ISSUE THREAD

**Issue by andreas-repp** [openapi-tools/jackson-dataformat-hal#28]
Currently, whenever you create a `HALLink` from a `String` with the Builder, the `templated` field is set. 

I don't have templated links but they are only relative paths and therefore not valid URIs. However, I also don't want to always send the `templated` field. What would be the best way to achieve this?

**Comment by langecode** [comment]
Sorry for the late answer.

A relative path is a perfectly ok URI - not URL - but URI. However, the Java `URI` class do not support templated URIs hence we had to implement those as strings.

See [Java SE documentation for URI class](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/net/URI.html) as well as [RFC 2396](https://www.ietf.org/rfc/rfc2396.txt).

**Comment by andreas-repp** [comment]
Could it be an option to add another constructor for `HALLink.Builder` with this parameters `Builder(String href, Boolean templated)`? This way if you want to create a `HALLink` object from a string without setting the `templated` flag, you could just create it with null as the parameter.

**Comment by langecode** [comment]
I think that could be an option, yes. However, I guess that would basically be wrapping `URI.create(href)` when templated is `false` - but it might make for an easier to understand API.
