### ISSUE TITLE
Forked from my account

### ISSUE THREAD

**Issue by arucard21** [openapi-tools/jackson-dataformat-hal#29]
I'm not sure why the openapi-tools repo was forked from my account. But since the openapi-tools repo should probably be the main repo for this, should I just transfer ownership of my repo? 

I think that should remove the "forked from" message, though I'm not quite sure. But it shouldn't be too hard to find a way to do this.

**Comment by arucard21** [comment]
I found that I could just delete my own repo. That seems to have fixed it.

**Comment by langecode** [comment]
Yeah, I think actually it is because it was originally started within the Nykredit organization here. Then Nykredit chose to not support this open source project anymore and it was moved to "openapi-tools". Therefore your fork might have been older than this repo. Thanks for fixing this.
