### ISSUE TITLE
HAL Forms Support

### ISSUE THREAD

**Issue by jimhooker2002** [openapi-tools/jackson-dataformat-hal#3]
Thanks for a fantastic tool already.  Seems like this is growing in popularity and wouldn't be a big lift to add it to the existing library: https://rwcbook.github.io/hal-forms/

Wondering what your thoughts on that are?  Would you be opposed to pull requests adding this feature or do you see it as permanently out-of-scope for this library?

**Comment by jimhooker2002** [comment]
Withdrawing.  Upon closer reading of the spec, it's obvious that hal-forms is intended to be kept separate and not part of the same document as HAL itself.

**Comment by langecode** [comment]
Very glad that you find the HAL Jackson extension useful. I haven’t used HAL forms but browsing through the HAL forms specification I agree that this is a separate “add-on”. As mentioned I haven’t used HAL forms myself so I am not sure what best could aid in supporing this - I do see that there might be some benefit rendering the “_templates” property in some intelligent way. This could maybe be implemented similar to what we have done with _links and _embedded properties.
