### ISSUE TITLE
GitHub Actions broken

### ISSUE THREAD

**Issue by arucard21** [openapi-tools/jackson-dataformat-hal#39]
It seems something is wrong with the GitHub Actions. The build does not seem to start for any of the pull requests. It seems that something needs to be changed in the protected branch settings of the repository:
https://github.community/t/expected-waiting-for-status-to-be-reported/16727

Hope you can fix the settings this since it's blocking any PRs from being merged (by me at least).

Edit: @langecode looks like you can still merge the PRs. So it's less of a problem. Might still want to look into this though.

**Comment by langecode** [comment]
Yeah, I noticed that too. I'll take a look at it.

>

**Comment by arucard21** [comment]
Seems like commit d24e59dbd2b18981b9a40e544e10a448da13ffc3 fixed this. I verified this with PR #41.
