### ISSUE TITLE
CURIE Provider

### ISSUE THREAD

**Issue by jimhooker2002** [openapi-tools/jackson-dataformat-hal#4]
Thinking about how we might make CURIE generation simpler for this library rather than have to specify them for all of our resources.  Thought I'd throw the following idea out there for discussion....

1: Support optional CurieProvider interface to be provided when instantiating HALMapper.
2: CurieProvider interface used in serializer.  When a link of the form "foo:bar" detected (contains colon) then CURIE automatically generated by CurieProvider implementation.

This would allow CurieProvider class to turn these three links "foo:bar", "foo:bar2" and "flibble:flip" links into e.g.

"_links": {
    "curies": [
       {
            "name": "foo",
            "href": "http://my.api.com/docs/rels/foo-{rel},
            "templated": true 
        },
       {
            "name": "flibble",
            "href": "http://my.api.com/docs/rels/flibble-{rel},
            "templated": true 
        }
    ]
}

Note that I never had to specify the curies link in my resource class, it just showed up during serialization.  It was summoned into existence upon detection of links containing a colon, the serializer then delegated to a CurieProvider implementation.

Thought I'd share the idea in case there is merit in it.  Happy to scratch a PR if there is.  Feel free to close if you feel like this is a dead-end however.

**Comment by langecode** [comment]
I have also had thoughts about extending the mapper with some kind of support for the curie part of HAL. Haven't got to it yet but by all means feels free to take a shot and do a PR.

**Comment by jimhooker2002** [comment]
Took a first swipe at getting something working: https://github.com/openapi-tools/jackson-dataformat-hal/pull/5/commits

**Comment by langecode** [comment]
Been looking through the PR it strikes me that we have two approaches here (at least :-) ).

Reading the HAL specification it recommends using URLs as the rels and the curies are introduced to simplify this by making it possible to use a more "logic" identifier for the URL identifying the rel.

I am thinking that we could take an approach where the rel is still not treated like an URL (like most cases I have seen) but we introduce, e.g., the `CurieProvider`, to add the curie section purely for documentation.

An alternative approach would be to actually define the rel as an URL but teach the framework to simplify this during serialization - something like 

```java
@Resource
@Curies({@Curie(href = "http://docs.my.site/{rel}", curie = "cur1")})
class Model {
    @Link(value = "http://docs.my.site/rel1", curie = "cur1")) // the curie property referencing the curies
    HALLink link;
}
```

or maybe the `@Link` `value` could be only the rel:
```java
@Resource
@Curies({@Curie(href = "http://docs.my.site/{rel}", curie = "cur1")})
class Model {
    @Link(value = "rel1", curie = "cur1")) // this would actually imply that 'value' changes semantic slightly when the 'curie' property is present - not sure that is desirable
    HALLink link;
}
```

generating an output like

```json
"_links": {
  "curies": [
      {
        "name": "cur1",
        "href": "http://docs.my.site/{rel}",
        "templates": true
      }
  ],
  "cur1:rel1": { "href": "..." }
}
```

My point being that in the second approach the link is actually created with the URL rel and the curie template defined to "automagically" substitute the URL during serialization. In the deserialization scenario this would allow the framework to deserialize the link with either a full URL as rel or with a correctly defined curie - and if the curie is not referenced in the `@Link` the current working is maintained.

Don't know if I am making sense here? :-) I am just wondering whether we should keep the curies strictly as a convenient documentation or if we should teach the framework to understand curies to simplify URL rels.

**Comment by jimhooker2002** [comment]
Thanks for detailed thoughts and feedback.  You are making sense :-) 

Another couple of thoughts/complications to throw into the mix here; can CURIE construction always be achieved via annotations (known at compile-time) or can run-time information also be used?  For example, my documentation links point to my service which is deployed through a number of stages on the way to production (different test environments).  The URL is of the form:

http://docs.my.site/stage-name-goes-here/{rel}

Where stage name can be alpha, beta, gamma, production etc.  The stage name is only known at run-time (provided by stage specific configuration). The run-time knowledge required of the stage name is problematic in the annotation case.

Another (very minor) thought is that CURIE format tends to be very formulaic for a service, following a predictable pattern and duplicating (typically) the base of the URI.  Using annotations tends to lead to slightly more duplication in the code rather than just "coding the rule".  Like I say, a minor and manageable point of course.

Advantages of the annotations are: less magic, more explicit.  Deserialisation supported. 

I could make the pure annotation driven approach work if needs be, I'd just nominate a stage as the "documentation" provider (accepting that the docs will be slightly out of date for the other stages from time-to-time).  

Slight pref for the following style (your second example): @Link(value = "rel1", curie = "cur1"))

**Comment by jimhooker2002** [comment]
Hmmm, perhaps the stage name issue is solvable actually.  href in the CURIE is templated after all.  I'd assumed (until now) that the only permissible template variable in the CURIE href was 'rel'.  Perhaps it's OK to also add {stage-name}/{rel} indicating that stage-name should be provided at run-time.  I don't think that violates the HAL spec in anyway.  In which case the annotation supports different doc links per stage and my first point above is invalid.

**Comment by arucard21** [comment]
First off, this sounds like a good idea and I also like the style from the second example.

I don't think the different URLs for a deployed service should be a problem for CURIEs. Any URL that is relative to the deployed service can be defined as a normal relative or root-relative URL. So a CURIE would not be needed there.

And from the [draft spec](https://tools.ietf.org/html/draft-kelly-json-hal-08#section-8.2), the `rel` template variable is the only one that seems to be allowed. The draft spec refers to the use of CURIE Syntax from the CURIE specification which does not mention template variables at all. So the `rel` variable seems to be something defined in the HAL+JSON draft spec and it does not seem to allow other template variables. (I'm not too familiar with these specifications, so I might be wrong about this)

**Comment by jimhooker2002** [comment]
Thanks for thoughts all.  I've not forgotten about this.  Working on the next rev based on previous code review comments now.  Currently taking a swipe at the annotation based approach (second example flavour).  Will submit for, errrr, second-round "initial" comments soon ;-)

**Comment by jimhooker2002** [comment]
Ding ding, round 2!

https://github.com/openapi-tools/jackson-dataformat-hal/pull/6

**Comment by langecode** [comment]
Thanks appreciate your work. I will try to find some time to go through the PR as soon as possible. :-)

**Comment by langecode** [comment]
Implementation provided by release [1.0.5](https://github.com/openapi-tools/jackson-dataformat-hal/tree/v1.0.5). @jimhooker2002 thanks for your participation.
